spring.application.name=EduSecure

server.port=${SERVER_PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/edusecure}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.open-in-view=false

jwt.secret=${JWT_SECRET:QmFja2VuZEZvckVkdVNlY3VyZVN0dWR5UHJvamVjdEhlbHBTaWduaW5nS2V5MTIzNDU2Nzg5MDEyMzQ1Njc4OTA=}
jwt.expiration=${JWT_EXPIRATION:86400000}

