package edusecure.edusecure.entity.audit;

public enum AuditActionType {
    ASSIGNMENT_CREATED,
    USER_CREATED,
    SPACE_CREATED,
    SPACE_UPDATED,
    SPACE_STUDENT_ADDED,
    SPACE_STUDENT_REMOVED,
    SPACE_REGISTRATION_REQUEST_CREATED,
    SPACE_REGISTRATION_REQUEST_APPROVED,
    SPACE_REGISTRATION_REQUEST_REJECTED,
    SPACE_REGISTRATION_REQUEST_CANCELLED,
    EXAM_CREATED,
    EXAM_UPDATED,
    EXAM_RESULT_CREATED,
    EXAM_RESULT_UPDATED,
    SUBMISSION_CREATED,
    SUBMISSION_VERIFIED,
    SUBMISSION_VERIFICATION_FAILED,
    SUBMISSION_CONTENT_ACCESSED,
    GRADE_CREATED,
    GRADE_UPDATED
}