package edusecure.edusecure.entity.audit;

public enum AuditActionType {
    ASSIGNMENT_CREATED,
    SUBMISSION_CREATED,
    SUBMISSION_VERIFIED,
    SUBMISSION_VERIFICATION_FAILED,
    SUBMISSION_CONTENT_ACCESSED,
    GRADE_CREATED,
    GRADE_UPDATED
}